version: "3.4"
services:
  app:
    build:
      context: .
      target: build
    environment:
      - NODE_ENV=production
      - WORKDIR=/app
    volumes:
      - ./public:/app/packages/web/public
