/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const file = require("../assets/island.gltf").default;

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(file);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[-0.01, 0, 0]}
        scale={[4.24, 0.32, 3.88]}
      />
      <mesh
        geometry={nodes["Grass_Seamless_Texture_#1417"].geometry}
        material={materials["Grass Seamless Texture #1417"]}
        position={[-0.51, 0.73, 0]}
      />
    </group>
  );
}

useGLTF.preload(file);
